// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/list-my-groups.ts
import { createClient } from "npm:@supabase/supabase-js@^2.90.1";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
function supabaseForUser(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_my_groups_default = defineTool({
  name: "list_my_groups",
  title: "List my study groups",
  description: "List LoopiFy study groups the signed-in user belongs to (both peer study groups and learning groups).",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const sb = supabaseForUser(ctx);
    const userId = ctx.getUserId();
    const [studyRes, learningRes] = await Promise.all([
      sb.from("group_members").select("group_id, study_groups(id, name, description, subject, created_at)").eq("user_id", userId),
      sb.from("group_learning_members").select("group_id, study_groups(id, name, description, subject, created_at)").eq("user_id", userId)
    ]);
    if (studyRes.error) {
      return { content: [{ type: "text", text: studyRes.error.message }], isError: true };
    }
    if (learningRes.error) {
      return { content: [{ type: "text", text: learningRes.error.message }], isError: true };
    }
    const rows = [
      ...(studyRes.data ?? []).map((r) => ({ kind: "study", ...r.study_groups })),
      ...(learningRes.data ?? []).map((r) => ({ kind: "learning", ...r.study_groups }))
    ].filter((r) => r && r.id);
    return {
      content: [{ type: "text", text: JSON.stringify(rows, null, 2) }],
      structuredContent: { groups: rows }
    };
  }
});

// src/lib/mcp/tools/list-group-lectures.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.90.1";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^3.25.76";
function supabaseForUser2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_group_lectures_default = defineTool2({
  name: "list_group_lectures",
  title: "List lectures in a group",
  description: "List lectures published in a LoopiFy learning group the signed-in user belongs to.",
  inputSchema: {
    group_id: z.string().uuid().describe("Study group UUID")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ group_id }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await supabaseForUser2(ctx).from("lectures").select("id, title, description, video_url, created_at").eq("group_id", group_id).order("created_at", { ascending: false });
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { lectures: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-my-assignments.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.90.1";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^3.25.76";
function supabaseForUser3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_my_assignments_default = defineTool3({
  name: "list_my_assignments",
  title: "List my assignments",
  description: "List assignments across LoopiFy groups the signed-in user belongs to. Optionally filter by a specific group.",
  inputSchema: {
    group_id: z2.string().uuid().optional().describe("Optional group UUID to filter by")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ group_id }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const sb = supabaseForUser3(ctx);
    let query = sb.from("assignments").select("id, group_id, title, description, due_date, created_at").order("due_date", { ascending: true, nullsFirst: false });
    if (group_id) query = query.eq("group_id", group_id);
    const { data, error } = await query;
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { assignments: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-my-flashcard-decks.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.90.1";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.20.0";
function supabaseForUser4(ctx) {
  return createClient4(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_my_flashcard_decks_default = defineTool4({
  name: "list_my_flashcard_decks",
  title: "List my flashcard decks",
  description: "List flashcard decks the signed-in user can view on LoopiFy.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await supabaseForUser4(ctx).from("flashcard_decks").select("id, title, description, group_id, created_at").order("created_at", { ascending: false });
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { decks: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-my-streak.ts
import { createClient as createClient5 } from "npm:@supabase/supabase-js@^2.90.1";
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.20.0";
function supabaseForUser5(ctx) {
  return createClient5(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_my_streak_default = defineTool5({
  name: "get_my_streak",
  title: "Get my learning streak",
  description: "Get the signed-in user's current LoopiFy learning streak and longest streak.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await supabaseForUser5(ctx).from("user_streaks").select("current_streak, longest_streak, last_activity_date").eq("user_id", ctx.getUserId()).maybeSingle();
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    const payload = data ?? { current_streak: 0, longest_streak: 0, last_activity_date: null };
    return {
      content: [{ type: "text", text: JSON.stringify(payload, null, 2) }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "lkyyfdsamiqhweuthpbf";
var mcp_default = defineMcp({
  name: "loopify-mcp",
  title: "LoopiFy",
  version: "0.1.0",
  instructions: "Tools for LoopiFy, a peer study app. Use these to read the signed-in student's groups, lectures, assignments, flashcard decks, and learning streak. All tools are read-only and scoped to the authenticated user.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    list_my_groups_default,
    list_group_lectures_default,
    list_my_assignments_default,
    list_my_flashcard_decks_default,
    get_my_streak_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
